package myapp.dao;

import java.util.Date;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.EntityTransaction;
import javax.persistence.PersistenceException;

import myapp.model.Person;

public class TestDao {

   static Dao dao;

   @BeforeAll
   public static void beforeAll() {
      dao = new Dao();
      dao.init();
   }

   @AfterAll
   public static void afterAll() {
      dao.close();
   }

   @BeforeEach
   public void setUp() {
      // pour plus tard
   }

   @AfterEach
   public void tearDown() {
      // pour plus tard
   }

   @Test
   public void testVide() {
	   
   }
   
   @Test
   public void testAddPerson() {
	   //TODO: Il ne faut pas setId car AutoGenerated car sinon "detached entity problem"
	   EntityManagerFactory emf = Persistence.createEntityManagerFactory("myBase");    
	    EntityManager em = emf.createEntityManager();    
	    EntityTransaction transac = em.getTransaction();
	    transac.begin();
	    Person nouvellePersonne = new Person();
	    nouvellePersonne.setFirstName("LOLILOL");
	    dao.addPerson(nouvellePersonne);
   }
   
   /*Vérification 1 : Ajoutez un test unitaire afin de valider la création d'une personne et sa relecture.
   Vérifiez dans la table les informations ajoutées.*/
   @Test
   public void testCreationEtRelecturePersonne(){
	   System.out.println();
	   
       Person p = new Person();
       p.setFirstName("Victorinne");
       Date birthday = new Date();
       birthday.setYear(1998);
       birthday.setMonth(3);
       birthday.setDate(17);
       p.setBirthDay(birthday);

       System.out.println("Je add Victorinette");
       dao.addPerson(p);
       System.out.println("gg c'est add");
       Person pulledPerson = dao.findPerson(5);
       System.out.println("J'ai récup Victorinette");
       /*TODO: Comment comparer objets par champs et non références ???*/
       Assertions.assertEquals(pulledPerson, p);

   }

   /*Testez la génération des erreurs dues à deux personnes ayant le même prénom (remarquez la clause unique
   de la propriété firstName).*/
   @Test
   public void test2PersonWithSameId(){

   }

   @Test
   public void testFindAllPerson(){
       System.out.println("Liste de toutes les personnes "+dao.findAllPersons());
   }

}